[package]
name = "plant-ui-app"
version.workspace = true
edition.workspace = true

[dependencies]
plant-ui.workspace = true
plant-ui-data.workspace = true
egui.workspace = true
eframe.workspace = true
egui-phosphor.workspace = true
egui_inspection.workspace = true
tokio.workspace = true
anyhow.workspace = true